### PR TITLE
Automated PR: Standardising Files

### PR DESCRIPTION
**Pull request by xorimabot**
This PR will standardise the files we have with out agreed spec in sous-chefs/repo-management, this repo has been identified as a circleci orb repo by topic of orb

### CODE REVIEW

**Review by xorima — DISMISSED** [review]

**Comment by damacus** [comment]
Feels a bit weird to be running Github actions on a CircleCI orb repo 🤔

**Comment by xorima** [comment]
I kind of agree, but all of our linting runs on Github Actions and is the stuff we know works was my thought? 

Standard seems to be github actions with circle running danger nowdays

**Comment by damacus** [comment]
I would say, we *did* know CircleCI. And we still have these orbs kicking around. If we're doing away with CircleCI for this repo, we should also do away with this repo and the orb

**Review by xorima — APPROVED** [review]

**Comment by xorima** [comment]
Looking at our repos our only use of circleci is for danger now, I think this orb and it's maintenance do come into question, if your around for the meeting this week lets discuss it then?

**Pull request closed without merging**
